### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by IgorB20** [IgorB20/formula1-game#1]
### TODO
- [ ] Menu inical
- [ ] Colisão com paredes mais externas (pra não deixar o carrinho sair da textura da pista)
- [ ] Colisão com paredes da pista
- [ ] Incrementar volta atual do carro sempre que ele passar pela largada
- [ ] Contador antes da corrida começar
